### ISSUE TITLE
Upload of favicon.ico

### ISSUE THREAD

**Issue by JamesEdmonds89** [chrisbrownie/Invoke-AdfsBranding#2]
Hi,

Am I misunderstanding the use of the section around setting the FavIcon?

It appears that it is setting the favicon.ico as the onload.js?
    if ($faviconExists) {
        $AdditionalFileResources += @{
             Uri = "/adfs/portal/logo/favicon.ico"
             Path = "$(Join-Path $CustomThemePath "script\onload.js")"

Should the path, not be the path to the favicon.ico file?

Cheers
Eds

**Comment by JamesEdmonds89** [comment]
I got it working when doing this section on its own, by specifying file name/path of the icon, not the js

Cheers
Eds

**Comment by chrisbrownie** [comment]
@JamesEdmonds89 good pickup, that must've been a copy/paste error at some point. I'll get this resolved.
